spring:
  application:
    name: order-service
  cloud:
    config:
      override-none: true
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin




server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
#暴露hystrix端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#启用hystrix
feign:
  hystrix:
    enabled: true
    
